apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: example-rule
spec:
  rules:
    - name: "example rule"
      labels:
        "example-custom-feature": "true"
        "foooooooo": "bar"
        "abc": "def"
        "def": "ghi"
      matchFeatures:
        - feature: kernel.config
          matchExpressions:
            64BIT: {op: In, value: ["y"]}

