apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: my-sample-rule-object
spec:
  rules:
    - name: "my sample rule"
      labels:
        "my-sample-feature": "true"
# Using tainting feature requires the feature gate (--allowTainting) to be enabled
      taints:
        - effect: PreferNoSchedule
          key: bar
          value: "true"
        - effect: NoExecute
          key: foo
          value: "true"
      matchFeatures:
        - feature: kernel.loadedmodule
          matchExpressions:
            dummy: {op: Exists}
        - feature: kernel.config
          matchExpressions:
            X86: {op: In, value: ["y"]}
