name: Project Checks

on:
  push:
    branches:
      - master
      - "release/**"
      - "test/**"
  pull_request:
    branches:
      - master
      - "release/**"

jobs:
  verify:
    name: Minimal PR Verification
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
      - name: make verify
        run: |
          make test
      - name: make codecov
        run: |
          make upload
