name: Verify
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3